farms:
  key:
    block:
    minDelay:
    maxDelay:
    star:
      x:
      y:
      z:

mines:
  key:
    loc1:
      x:
      y:
      z:
    loc2:
      x:
      y:
      z:
    minDelay:
    maxDelay:
    world:

trees:
  key:
    loc1:
      x:
      y:
      z:
    loc2:
      x:
      y:
      z:
    minDelay:
    maxDelay:
    world:

    